import math

TILE_SIZE = 32

MINIMAP_SCALE_FACTOR = 0.2

TILE_VERTICAL_COUNT = 20
TILE_HORIZONTAL_COUNT = 30

RENDER_WIDTH = TILE_HORIZONTAL_COUNT * TILE_SIZE
RENDER_HEIGHT = TILE_VERTICAL_COUNT * TILE_SIZE

MINIMAP_TILE_SIZE = math.ceil(TILE_SIZE * MINIMAP_SCALE_FACTOR)

MINI_MAP_WIDTH = TILE_HORIZONTAL_COUNT * MINIMAP_TILE_SIZE
MINI_MAP_HEIGHT = TILE_VERTICAL_COUNT * MINIMAP_TILE_SIZE

FOV = math.radians(90)
WALL_WIDTH = 2
NUM_RAYS = int(RENDER_WIDTH / WALL_WIDTH)
DISTANCE_BETWEEN_RAYS = FOV / NUM_RAYS  # Cast rays for the left half of the screen

TEXTURE_WIDTH = 64
TEXTURE_HEIGHT = 64

DISTANCE_TO_PROJECTION_PLANE = ((RENDER_WIDTH / 2) / math.tan(FOV / 2))

